[project]
name = "slm-gerenciadordespesas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thiago Romero", email = "tnromero@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
    "pydantic>=2.13.5",
]

[project.scripts]
slm-gerenciadordespesas = "slm_gerenciadordespesas:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
